# Generated by Django 5.0.3 on 2024-04-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="room_name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
